In [33]:
import numpy as np
import pandas as pd
import csv

In [34]:
with open("output.csv", "r") as file:
    labels = pd.read_csv("output.csv", header = None)
    labels = np.array(labels)
    print(labels.shape)
    print(labels)
    
    labels = pd.read_csv("output.csv", header = None)
    popped = labels.pop(514)
    popped = labels.pop(0)
    popped = labels.pop(513)
    labels = np.array(labels)
    print(labels.shape)
    print(labels)

(512, 515)
[[0 0 0 ... 0 18 ' ']
 [1 0 0 ... 0 20 ' ']
 [2 0 0 ... 0 24 ' ']
 ...
 [509 0 0 ... 0 21 ' ']
 [510 0 0 ... 0 22 ' ']
 [511 0 0 ... 0 24 ' ']]
(512, 512)
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [35]:
print(np.max(labels, axis = 1))
print(np.argmax(labels[0]))

[2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 1 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 

In [36]:
for r in range(labels.shape[0]):
    for c in range(labels.shape[1]):
        if (labels[r][c] >= 1):
            print("Hammering page " + str(r) + " has " + str(labels[r][c]) + " errors at page " + str(c))

Hammering page 0 has 1 errors at page 99
Hammering page 0 has 1 errors at page 122
Hammering page 0 has 2 errors at page 124
Hammering page 0 has 1 errors at page 134
Hammering page 0 has 1 errors at page 139
Hammering page 0 has 1 errors at page 157
Hammering page 0 has 1 errors at page 163
Hammering page 0 has 1 errors at page 172
Hammering page 0 has 1 errors at page 178
Hammering page 0 has 1 errors at page 329
Hammering page 0 has 1 errors at page 355
Hammering page 0 has 1 errors at page 378
Hammering page 0 has 1 errors at page 380
Hammering page 0 has 1 errors at page 390
Hammering page 0 has 1 errors at page 395
Hammering page 0 has 1 errors at page 419
Hammering page 0 has 1 errors at page 428
Hammering page 0 has 1 errors at page 434
Hammering page 1 has 1 errors at page 92
Hammering page 1 has 1 errors at page 99
Hammering page 1 has 1 errors at page 122
Hammering page 1 has 2 errors at page 124
Hammering page 1 has 1 errors at page 139
Hammering page 1 has 1 errors at page

Hammering page 62 has 1 errors at page 134
Hammering page 62 has 1 errors at page 139
Hammering page 62 has 1 errors at page 157
Hammering page 62 has 1 errors at page 163
Hammering page 62 has 1 errors at page 172
Hammering page 62 has 1 errors at page 178
Hammering page 62 has 1 errors at page 329
Hammering page 62 has 1 errors at page 348
Hammering page 62 has 1 errors at page 355
Hammering page 62 has 1 errors at page 378
Hammering page 62 has 2 errors at page 380
Hammering page 62 has 1 errors at page 390
Hammering page 62 has 1 errors at page 395
Hammering page 62 has 1 errors at page 413
Hammering page 62 has 1 errors at page 419
Hammering page 62 has 1 errors at page 434
Hammering page 63 has 1 errors at page 73
Hammering page 63 has 1 errors at page 92
Hammering page 63 has 1 errors at page 99
Hammering page 63 has 1 errors at page 113
Hammering page 63 has 1 errors at page 122
Hammering page 63 has 2 errors at page 124
Hammering page 63 has 1 errors at page 134
Hammering page

Hammering page 79 has 2 errors at page 380
Hammering page 79 has 1 errors at page 390
Hammering page 79 has 1 errors at page 395
Hammering page 79 has 1 errors at page 397
Hammering page 79 has 1 errors at page 419
Hammering page 79 has 1 errors at page 428
Hammering page 80 has 1 errors at page 92
Hammering page 80 has 1 errors at page 99
Hammering page 80 has 1 errors at page 113
Hammering page 80 has 1 errors at page 122
Hammering page 80 has 2 errors at page 124
Hammering page 80 has 1 errors at page 139
Hammering page 80 has 1 errors at page 141
Hammering page 80 has 1 errors at page 157
Hammering page 80 has 1 errors at page 163
Hammering page 80 has 1 errors at page 172
Hammering page 80 has 1 errors at page 178
Hammering page 80 has 1 errors at page 329
Hammering page 80 has 1 errors at page 348
Hammering page 80 has 1 errors at page 355
Hammering page 80 has 1 errors at page 378
Hammering page 80 has 2 errors at page 380
Hammering page 80 has 1 errors at page 395
Hammering pag

Hammering page 152 has 1 errors at page 172
Hammering page 152 has 1 errors at page 178
Hammering page 152 has 1 errors at page 329
Hammering page 152 has 1 errors at page 348
Hammering page 152 has 1 errors at page 355
Hammering page 152 has 1 errors at page 378
Hammering page 152 has 2 errors at page 380
Hammering page 152 has 1 errors at page 395
Hammering page 152 has 1 errors at page 397
Hammering page 152 has 1 errors at page 413
Hammering page 152 has 1 errors at page 418
Hammering page 152 has 1 errors at page 419
Hammering page 152 has 1 errors at page 428
Hammering page 152 has 1 errors at page 434
Hammering page 153 has 1 errors at page 73
Hammering page 153 has 1 errors at page 92
Hammering page 153 has 1 errors at page 99
Hammering page 153 has 1 errors at page 113
Hammering page 153 has 1 errors at page 122
Hammering page 153 has 2 errors at page 124
Hammering page 153 has 1 errors at page 134
Hammering page 153 has 1 errors at page 139
Hammering page 153 has 1 errors at 

Hammering page 163 has 1 errors at page 329
Hammering page 163 has 1 errors at page 348
Hammering page 163 has 1 errors at page 355
Hammering page 163 has 1 errors at page 378
Hammering page 163 has 2 errors at page 380
Hammering page 163 has 1 errors at page 390
Hammering page 163 has 1 errors at page 395
Hammering page 163 has 1 errors at page 419
Hammering page 163 has 1 errors at page 428
Hammering page 163 has 1 errors at page 434
Hammering page 164 has 1 errors at page 73
Hammering page 164 has 1 errors at page 99
Hammering page 164 has 1 errors at page 113
Hammering page 164 has 1 errors at page 122
Hammering page 164 has 2 errors at page 124
Hammering page 164 has 1 errors at page 134
Hammering page 164 has 1 errors at page 139
Hammering page 164 has 1 errors at page 153
Hammering page 164 has 1 errors at page 157
Hammering page 164 has 1 errors at page 162
Hammering page 164 has 1 errors at page 163
Hammering page 164 has 1 errors at page 178
Hammering page 164 has 1 errors at

Hammering page 176 has 1 errors at page 172
Hammering page 176 has 1 errors at page 178
Hammering page 176 has 1 errors at page 329
Hammering page 176 has 1 errors at page 348
Hammering page 176 has 1 errors at page 355
Hammering page 176 has 1 errors at page 369
Hammering page 176 has 1 errors at page 378
Hammering page 176 has 2 errors at page 380
Hammering page 176 has 1 errors at page 395
Hammering page 176 has 1 errors at page 397
Hammering page 176 has 1 errors at page 418
Hammering page 176 has 1 errors at page 419
Hammering page 176 has 1 errors at page 428
Hammering page 176 has 1 errors at page 434
Hammering page 177 has 1 errors at page 73
Hammering page 177 has 1 errors at page 99
Hammering page 177 has 1 errors at page 122
Hammering page 177 has 2 errors at page 124
Hammering page 177 has 1 errors at page 139
Hammering page 177 has 1 errors at page 153
Hammering page 177 has 1 errors at page 163
Hammering page 177 has 1 errors at page 178
Hammering page 177 has 1 errors at

Hammering page 232 has 1 errors at page 153
Hammering page 232 has 1 errors at page 157
Hammering page 232 has 1 errors at page 163
Hammering page 232 has 1 errors at page 172
Hammering page 232 has 1 errors at page 178
Hammering page 232 has 1 errors at page 329
Hammering page 232 has 1 errors at page 355
Hammering page 232 has 1 errors at page 369
Hammering page 232 has 1 errors at page 378
Hammering page 232 has 2 errors at page 380
Hammering page 232 has 1 errors at page 395
Hammering page 232 has 1 errors at page 397
Hammering page 232 has 1 errors at page 413
Hammering page 232 has 1 errors at page 419
Hammering page 232 has 1 errors at page 428
Hammering page 232 has 1 errors at page 434
Hammering page 233 has 1 errors at page 73
Hammering page 233 has 1 errors at page 99
Hammering page 233 has 1 errors at page 113
Hammering page 233 has 1 errors at page 122
Hammering page 233 has 1 errors at page 124
Hammering page 233 has 1 errors at page 134
Hammering page 233 has 1 errors at

Hammering page 255 has 1 errors at page 163
Hammering page 255 has 1 errors at page 172
Hammering page 255 has 1 errors at page 355
Hammering page 255 has 1 errors at page 378
Hammering page 255 has 2 errors at page 380
Hammering page 255 has 1 errors at page 395
Hammering page 255 has 1 errors at page 397
Hammering page 255 has 1 errors at page 419
Hammering page 255 has 1 errors at page 434
Hammering page 256 has 1 errors at page 73
Hammering page 256 has 1 errors at page 99
Hammering page 256 has 1 errors at page 122
Hammering page 256 has 2 errors at page 124
Hammering page 256 has 1 errors at page 134
Hammering page 256 has 1 errors at page 139
Hammering page 256 has 1 errors at page 153
Hammering page 256 has 1 errors at page 157
Hammering page 256 has 1 errors at page 162
Hammering page 256 has 1 errors at page 163
Hammering page 256 has 1 errors at page 172
Hammering page 256 has 1 errors at page 178
Hammering page 256 has 1 errors at page 329
Hammering page 256 has 1 errors at

Hammering page 269 has 1 errors at page 139
Hammering page 269 has 1 errors at page 153
Hammering page 269 has 1 errors at page 157
Hammering page 269 has 1 errors at page 162
Hammering page 269 has 1 errors at page 163
Hammering page 269 has 1 errors at page 172
Hammering page 269 has 1 errors at page 178
Hammering page 269 has 1 errors at page 329
Hammering page 269 has 1 errors at page 352
Hammering page 269 has 1 errors at page 355
Hammering page 269 has 1 errors at page 369
Hammering page 269 has 1 errors at page 378
Hammering page 269 has 2 errors at page 380
Hammering page 269 has 1 errors at page 390
Hammering page 269 has 1 errors at page 395
Hammering page 269 has 1 errors at page 397
Hammering page 269 has 1 errors at page 409
Hammering page 269 has 1 errors at page 418
Hammering page 269 has 1 errors at page 419
Hammering page 269 has 1 errors at page 428
Hammering page 269 has 1 errors at page 434
Hammering page 270 has 1 errors at page 73
Hammering page 270 has 1 errors a

Hammering page 319 has 1 errors at page 355
Hammering page 319 has 1 errors at page 378
Hammering page 319 has 2 errors at page 380
Hammering page 319 has 1 errors at page 390
Hammering page 319 has 1 errors at page 395
Hammering page 319 has 1 errors at page 418
Hammering page 319 has 1 errors at page 419
Hammering page 319 has 1 errors at page 428
Hammering page 319 has 1 errors at page 434
Hammering page 320 has 1 errors at page 73
Hammering page 320 has 1 errors at page 96
Hammering page 320 has 1 errors at page 99
Hammering page 320 has 1 errors at page 122
Hammering page 320 has 2 errors at page 124
Hammering page 320 has 1 errors at page 134
Hammering page 320 has 1 errors at page 139
Hammering page 320 has 1 errors at page 157
Hammering page 320 has 2 errors at page 162
Hammering page 320 has 1 errors at page 163
Hammering page 320 has 1 errors at page 172
Hammering page 320 has 1 errors at page 178
Hammering page 320 has 1 errors at page 329
Hammering page 320 has 1 errors at 

Hammering page 350 has 1 errors at page 329
Hammering page 350 has 1 errors at page 355
Hammering page 350 has 1 errors at page 378
Hammering page 350 has 2 errors at page 380
Hammering page 350 has 1 errors at page 390
Hammering page 350 has 1 errors at page 395
Hammering page 350 has 1 errors at page 413
Hammering page 350 has 1 errors at page 418
Hammering page 350 has 1 errors at page 419
Hammering page 350 has 1 errors at page 434
Hammering page 351 has 1 errors at page 73
Hammering page 351 has 1 errors at page 92
Hammering page 351 has 1 errors at page 99
Hammering page 351 has 1 errors at page 122
Hammering page 351 has 2 errors at page 124
Hammering page 351 has 1 errors at page 134
Hammering page 351 has 1 errors at page 139
Hammering page 351 has 1 errors at page 141
Hammering page 351 has 1 errors at page 149
Hammering page 351 has 1 errors at page 157
Hammering page 351 has 1 errors at page 162
Hammering page 351 has 1 errors at page 163
Hammering page 351 has 1 errors at 

Hammering page 368 has 1 errors at page 418
Hammering page 368 has 1 errors at page 419
Hammering page 368 has 1 errors at page 428
Hammering page 368 has 1 errors at page 434
Hammering page 369 has 1 errors at page 73
Hammering page 369 has 1 errors at page 74
Hammering page 369 has 1 errors at page 96
Hammering page 369 has 1 errors at page 99
Hammering page 369 has 1 errors at page 122
Hammering page 369 has 2 errors at page 124
Hammering page 369 has 1 errors at page 139
Hammering page 369 has 1 errors at page 157
Hammering page 369 has 1 errors at page 162
Hammering page 369 has 1 errors at page 163
Hammering page 369 has 1 errors at page 172
Hammering page 369 has 1 errors at page 178
Hammering page 369 has 1 errors at page 329
Hammering page 369 has 1 errors at page 330
Hammering page 369 has 1 errors at page 355
Hammering page 369 has 1 errors at page 378
Hammering page 369 has 2 errors at page 380
Hammering page 369 has 1 errors at page 395
Hammering page 369 has 1 errors at p

Hammering page 404 has 1 errors at page 141
Hammering page 404 has 1 errors at page 157
Hammering page 404 has 1 errors at page 162
Hammering page 404 has 1 errors at page 163
Hammering page 404 has 1 errors at page 172
Hammering page 404 has 1 errors at page 178
Hammering page 404 has 1 errors at page 329
Hammering page 404 has 1 errors at page 355
Hammering page 404 has 1 errors at page 378
Hammering page 404 has 2 errors at page 380
Hammering page 404 has 1 errors at page 390
Hammering page 404 has 1 errors at page 395
Hammering page 404 has 1 errors at page 419
Hammering page 404 has 1 errors at page 428
Hammering page 404 has 1 errors at page 434
Hammering page 405 has 1 errors at page 73
Hammering page 405 has 1 errors at page 99
Hammering page 405 has 1 errors at page 122
Hammering page 405 has 2 errors at page 124
Hammering page 405 has 1 errors at page 134
Hammering page 405 has 1 errors at page 139
Hammering page 405 has 1 errors at page 153
Hammering page 405 has 1 errors at

Hammering page 447 has 1 errors at page 428
Hammering page 447 has 1 errors at page 434
Hammering page 448 has 1 errors at page 73
Hammering page 448 has 1 errors at page 99
Hammering page 448 has 1 errors at page 122
Hammering page 448 has 2 errors at page 124
Hammering page 448 has 1 errors at page 134
Hammering page 448 has 1 errors at page 139
Hammering page 448 has 1 errors at page 141
Hammering page 448 has 1 errors at page 153
Hammering page 448 has 1 errors at page 157
Hammering page 448 has 1 errors at page 162
Hammering page 448 has 1 errors at page 163
Hammering page 448 has 1 errors at page 172
Hammering page 448 has 1 errors at page 178
Hammering page 448 has 1 errors at page 329
Hammering page 448 has 1 errors at page 355
Hammering page 448 has 1 errors at page 378
Hammering page 448 has 2 errors at page 380
Hammering page 448 has 1 errors at page 395
Hammering page 448 has 1 errors at page 397
Hammering page 448 has 1 errors at page 409
Hammering page 448 has 1 errors at

Hammering page 459 has 1 errors at page 99
Hammering page 459 has 1 errors at page 122
Hammering page 459 has 2 errors at page 124
Hammering page 459 has 1 errors at page 134
Hammering page 459 has 1 errors at page 139
Hammering page 459 has 1 errors at page 141
Hammering page 459 has 1 errors at page 162
Hammering page 459 has 1 errors at page 163
Hammering page 459 has 1 errors at page 172
Hammering page 459 has 1 errors at page 178
Hammering page 459 has 1 errors at page 329
Hammering page 459 has 1 errors at page 355
Hammering page 459 has 1 errors at page 378
Hammering page 459 has 2 errors at page 380
Hammering page 459 has 1 errors at page 390
Hammering page 459 has 1 errors at page 395
Hammering page 459 has 1 errors at page 397
Hammering page 459 has 1 errors at page 418
Hammering page 459 has 1 errors at page 419
Hammering page 459 has 1 errors at page 428
Hammering page 459 has 1 errors at page 434
Hammering page 460 has 1 errors at page 73
Hammering page 460 has 1 errors at

Hammering page 499 has 1 errors at page 434
Hammering page 500 has 1 errors at page 73
Hammering page 500 has 1 errors at page 92
Hammering page 500 has 1 errors at page 99
Hammering page 500 has 1 errors at page 122
Hammering page 500 has 2 errors at page 124
Hammering page 500 has 1 errors at page 134
Hammering page 500 has 1 errors at page 139
Hammering page 500 has 1 errors at page 157
Hammering page 500 has 1 errors at page 162
Hammering page 500 has 1 errors at page 163
Hammering page 500 has 1 errors at page 172
Hammering page 500 has 1 errors at page 178
Hammering page 500 has 1 errors at page 329
Hammering page 500 has 1 errors at page 348
Hammering page 500 has 1 errors at page 355
Hammering page 500 has 1 errors at page 378
Hammering page 500 has 2 errors at page 380
Hammering page 500 has 1 errors at page 390
Hammering page 500 has 1 errors at page 395
Hammering page 500 has 1 errors at page 413
Hammering page 500 has 1 errors at page 418
Hammering page 500 has 1 errors at 

In [37]:
print(np.where(labels >= 1)[0])
print((np.where(labels >= 1)[0].shape))
print(np.max(labels, axis=1))
print((np.max(labels, axis=1)).shape)

[  0   0   0 ... 511 511 511]
(11373,)
[2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 1 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 

In [38]:
print(np.array(np.where(labels[0, :] >= 1)))
print(np.array(np.where(labels[0, :] >= 1)).shape)


[[ 99 122 124 134 139 157 163 172 178 329 355 378 380 390 395 419 428 434]]
(1, 18)


In [39]:
errors = {}
for i in range(labels.shape[0]):
    errors.update({i : (np.array(np.where(labels[i, :] >= 1))).flatten()})

In [40]:
print(errors)

{0: array([ 99, 122, 124, 134, 139, 157, 163, 172, 178, 329, 355, 378, 380,
       390, 395, 419, 428, 434], dtype=int64), 1: array([ 92,  99, 122, 124, 139, 141, 157, 163, 172, 178, 348, 355, 378,
       380, 390, 395, 413, 419, 428, 434], dtype=int64), 2: array([ 73,  92,  99, 113, 122, 124, 139, 141, 153, 163, 172, 178, 329,
       355, 378, 380, 390, 395, 397, 409, 413, 419, 428, 434], dtype=int64), 3: array([ 73,  99, 122, 124, 134, 139, 141, 157, 163, 178, 329, 355, 378,
       380, 390, 395, 397, 413, 419, 428, 434], dtype=int64), 4: array([ 73,  92,  99, 122, 124, 139, 141, 153, 163, 178, 355, 369, 378,
       380, 395, 419, 428, 434], dtype=int64), 5: array([ 73,  99, 122, 124, 134, 139, 141, 163, 172, 178, 329, 355, 378,
       380, 390, 395, 397, 413, 418, 419, 428, 434], dtype=int64), 6: array([ 73,  92,  99, 122, 124, 134, 139, 141, 153, 157, 163, 172, 178,
       329, 348, 355, 378, 380, 390, 395, 397, 419, 428, 434], dtype=int64), 7: array([ 73,  92,  99, 122, 124, 134, 

In [41]:
pageCount = {}
for i in errors.keys():
    arr = errors.get(i)
    for j in arr:
        if j in pageCount.keys():
            #val = pageCount.get(j)
            pageCount[j] += 1
        else:
            pageCount.update({j:1})
print(pageCount)

{99: 512, 122: 512, 124: 512, 134: 358, 139: 512, 157: 354, 163: 512, 172: 397, 178: 488, 329: 473, 355: 512, 378: 512, 380: 512, 390: 309, 395: 512, 419: 512, 428: 403, 434: 498, 92: 171, 141: 283, 348: 144, 413: 316, 73: 478, 113: 105, 153: 166, 397: 284, 409: 125, 369: 77, 418: 321, 162: 346, 477: 1, 164: 10, 410: 1, 433: 1, 106: 5, 170: 1, 96: 54, 474: 3, 352: 24, 149: 11, 125: 1, 414: 3, 362: 3, 405: 2, 74: 15, 330: 8, 420: 3, 218: 3, 426: 2, 158: 3, 154: 2, 210: 1}


In [42]:
pageCountByVal = {k: v for k, v in sorted(pageCount.items(), key=lambda item: item[1])}
print(pageCountByVal)
pageCountByKey = {k: v for k, v in sorted(pageCount.items(), key=lambda item: item[0])}
print()
print(pageCountByKey)
            

{477: 1, 410: 1, 433: 1, 170: 1, 125: 1, 210: 1, 405: 2, 426: 2, 154: 2, 474: 3, 414: 3, 362: 3, 420: 3, 218: 3, 158: 3, 106: 5, 330: 8, 164: 10, 149: 11, 74: 15, 352: 24, 96: 54, 369: 77, 113: 105, 409: 125, 348: 144, 153: 166, 92: 171, 141: 283, 397: 284, 390: 309, 413: 316, 418: 321, 162: 346, 157: 354, 134: 358, 172: 397, 428: 403, 329: 473, 73: 478, 178: 488, 434: 498, 99: 512, 122: 512, 124: 512, 139: 512, 163: 512, 355: 512, 378: 512, 380: 512, 395: 512, 419: 512}

{73: 478, 74: 15, 92: 171, 96: 54, 99: 512, 106: 5, 113: 105, 122: 512, 124: 512, 125: 1, 134: 358, 139: 512, 141: 283, 149: 11, 153: 166, 154: 2, 157: 354, 158: 3, 162: 346, 163: 512, 164: 10, 170: 1, 172: 397, 178: 488, 210: 1, 218: 3, 329: 473, 330: 8, 348: 144, 352: 24, 355: 512, 362: 3, 369: 77, 378: 512, 380: 512, 390: 309, 395: 512, 397: 284, 405: 2, 409: 125, 410: 1, 413: 316, 414: 3, 418: 321, 419: 512, 420: 3, 426: 2, 428: 403, 433: 1, 434: 498, 474: 3, 477: 1}


In [43]:
for i in range(512):
    if 410 in errors.get(i):
        print(i)

94


In [44]:
print(errors.get(59))

[ 73  99 122 124 134 139 141 153 162 163 178 329 355 378 380 395 397 413
 419 428 434 477]


In [45]:
hundredCount = 0
twodredCount = 0
threedredCount = 0
fourdredCount = 0
fivedredCount = 0
for i in pageCount.values():
    if i >= 100:
        hundredCount += 1
    if i >= 200:
        twodredCount += 1
    if i >= 300: 
        threedredCount += 1
    if i >= 400:
        fourdredCount += 1
    if i >= 500:
        fivedredCount += 1
print(hundredCount)
print(twodredCount)
print(threedredCount)
print(fourdredCount)
print(fivedredCount)

29
24
22
15
10


In [46]:
print(len(pageCount.keys()))

52


In [47]:
with open("block26AfterErase.csv", "r") as file:
    block26Pre = pd.read_csv("block26AfterErase.csv", header = None)
    block26Pre = np.array(block26Pre)
print(block26Pre)
print(block26Pre.shape)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 1 1 0 0 0 0 0 0 1 1
  0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0
  0 0 1 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 1 2 2 0 0 0 1 0 3 0 1 0 0 0 0 0 0
  1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 1 0 0 0 0
  0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1
  0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 1 0 1 2 1 0 0 0 1 0 3 0 1 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 

In [48]:
with open("block26Experiment.csv", "r") as file:
    block26Post = pd.read_csv("block26Experiment.csv", header = None)
    block26Post.pop(0)
    block26Post.pop(514)
    block26Post.pop(513)
    block26Post = np.array(block26Post)
print(block26Post)
print(block26Post.shape)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
(512, 512)


In [49]:
block26errors = block26Post-block26Pre
print(block26errors)
print(block26errors.shape)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
(512, 512)


In [50]:
print(np.where(block26Pre[0] >= 1))
print(np.where(block26Post[0] >= 1))
print(np.where(block26errors[0] >= 1))

(array([ 75,  91,  95,  98,  99, 106, 107, 112, 122, 124, 125, 139, 140,
       141, 146, 156, 158, 163, 164, 165, 169, 171, 173, 180, 189, 195,
       209, 234, 347, 354, 355, 362, 368, 378, 380, 395, 397, 412, 414,
       417, 419, 420, 421, 425, 427, 429, 445, 451, 465, 490, 494],
      dtype=int64),)
(array([ 91,  95,  98,  99, 106, 122, 124, 139, 141, 156, 158, 161, 163,
       164, 165, 169, 171, 173, 189, 195, 209, 347, 354, 355, 362, 378,
       380, 395, 406, 412, 414, 417, 419, 420, 425, 427, 429, 445, 451,
       465, 490], dtype=int64),)
(array([161, 406], dtype=int64),)


In [51]:
print(np.array(np.where(block26Post[0] >= 1)))
print(np.array(np.where(block26Pre[0] >= 1)).shape)
print(np.array(np.where(block26Post[0] >= 1)).shape)
print(np.array(np.where(block26errors[0] >= 1)).shape)

[[ 91  95  98  99 106 122 124 139 141 156 158 161 163 164 165 169 171 173
  189 195 209 347 354 355 362 378 380 395 406 412 414 417 419 420 425 427
  429 445 451 465 490]]
(1, 51)
(1, 41)
(1, 2)


In [52]:
print(np.min(block26errors, axis = 1))
print(np.min(block26errors, axis = 1).shape)

[-2 -2 -2 -2 -2 -2 -2 -2 -1 -1 -1 -2 -2 -2 -2 -2 -2 -2 -1 -1 -1 -1 -2 -1
 -2 -1 -1 -2 -1 -1 -1 -2 -2 -1 -2 -2 -2 -1 -2 -2 -2 -2 -2 -2 -2 -1 -2 -1
 -2 -2 -1 -2 -2 -2 -2 -1 -2 -1 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2
 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2
 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2
 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2
 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -1 -1 -1 -2 -2
 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -1 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2
 -2 -2 -2 -1 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -1 -2 -2 -2 -2 -2 -2
 -2 -2 -2 -2 -2 -2 -2 -2 -1 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2
 -2 -2 -2 -2 -1 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2
 -2 -2 -1 -2 -2 -1 -1 -2 -2 -2 -2 -1 -2 -1 -2 -1 -1 -2 -1 -1 -2 -1 -1 -1
 -1 -2 -2 -1 -1 -2 -1 -2 -1 -2 -2 -1 -1 -1 -2 -2 -1 -2 -2 -2 -1 -2 -2 -2
 -2 -2 -1 -1 -1 -1 -1 -2 -1 -2 -1 -2 -2 -2 -2 -2 -2

In [53]:
block26ErrorMap = {}
for i in range(block26errors.shape[0]):
    block26ErrorMap.update({i : (np.array(np.where(block26errors[i, :] >= 1))).flatten()})

In [54]:
print(block26ErrorMap)

{0: array([161, 406], dtype=int64), 1: array([161], dtype=int64), 2: array([161], dtype=int64), 3: array([133, 161], dtype=int64), 4: array([108, 161, 437], dtype=int64), 5: array([161, 234, 389], dtype=int64), 6: array([403], dtype=int64), 7: array([161], dtype=int64), 8: array([], dtype=int64), 9: array([], dtype=int64), 10: array([161], dtype=int64), 11: array([161, 238, 331], dtype=int64), 12: array([161], dtype=int64), 13: array([161], dtype=int64), 14: array([161, 201, 389, 396], dtype=int64), 15: array([161, 234], dtype=int64), 16: array([161, 389], dtype=int64), 17: array([133, 161, 389], dtype=int64), 18: array([161, 364], dtype=int64), 19: array([148, 490], dtype=int64), 20: array([161], dtype=int64), 21: array([161], dtype=int64), 22: array([161, 406], dtype=int64), 23: array([161], dtype=int64), 24: array([161], dtype=int64), 25: array([161], dtype=int64), 26: array([150, 161], dtype=int64), 27: array([150, 161, 181], dtype=int64), 28: array([161, 362], dtype=int64), 29: ar

In [55]:
block26pageCount = {}
for i in block26ErrorMap.keys():
    arr = block26ErrorMap.get(i)
    for j in arr:
        if j in block26pageCount.keys():
            #val = pageCount.get(j)
            block26pageCount[j] += 1
        else:
            block26pageCount.update({j:1})
print(block26pageCount)

{161: 277, 406: 41, 133: 73, 108: 56, 437: 25, 234: 97, 389: 42, 403: 8, 238: 1, 331: 62, 201: 43, 396: 26, 364: 28, 148: 1, 490: 70, 150: 36, 181: 66, 362: 36, 106: 55, 351: 9, 363: 81, 402: 57, 388: 1, 418: 3, 489: 54, 233: 59, 139: 7, 421: 47, 377: 13, 457: 31, 113: 24, 102: 62, 358: 36, 162: 9, 404: 2, 156: 20, 94: 35, 350: 20, 369: 20, 97: 20, 121: 29, 333: 84, 147: 14, 77: 126, 85: 1, 438: 3, 155: 22, 411: 6, 81: 3, 420: 7, 146: 11, 164: 10, 182: 15, 116: 11, 412: 3, 114: 6, 170: 3, 381: 4, 91: 3, 138: 2, 395: 1, 104: 4, 75: 2, 341: 1, 117: 1, 436: 3, 394: 2}


In [56]:
block26pageCountByVal = {k: v for k, v in sorted(block26pageCount.items(), key=lambda item: item[1])}
print(block26pageCountByVal)
block26pageCountByKey = {k: v for k, v in sorted(block26pageCount.items(), key=lambda item: item[0])}
print()
print(block26pageCountByKey)

{238: 1, 148: 1, 388: 1, 85: 1, 395: 1, 341: 1, 117: 1, 404: 2, 138: 2, 75: 2, 394: 2, 418: 3, 438: 3, 81: 3, 412: 3, 170: 3, 91: 3, 436: 3, 381: 4, 104: 4, 411: 6, 114: 6, 139: 7, 420: 7, 403: 8, 351: 9, 162: 9, 164: 10, 146: 11, 116: 11, 377: 13, 147: 14, 182: 15, 156: 20, 350: 20, 369: 20, 97: 20, 155: 22, 113: 24, 437: 25, 396: 26, 364: 28, 121: 29, 457: 31, 94: 35, 150: 36, 362: 36, 358: 36, 406: 41, 389: 42, 201: 43, 421: 47, 489: 54, 106: 55, 108: 56, 402: 57, 233: 59, 331: 62, 102: 62, 181: 66, 490: 70, 133: 73, 363: 81, 333: 84, 234: 97, 77: 126, 161: 277}

{75: 2, 77: 126, 81: 3, 85: 1, 91: 3, 94: 35, 97: 20, 102: 62, 104: 4, 106: 55, 108: 56, 113: 24, 114: 6, 116: 11, 117: 1, 121: 29, 133: 73, 138: 2, 139: 7, 146: 11, 147: 14, 148: 1, 150: 36, 155: 22, 156: 20, 161: 277, 162: 9, 164: 10, 170: 3, 181: 66, 182: 15, 201: 43, 233: 59, 234: 97, 238: 1, 331: 62, 333: 84, 341: 1, 350: 20, 351: 9, 358: 36, 362: 36, 363: 81, 364: 28, 369: 20, 377: 13, 381: 4, 388: 1, 389: 42, 394: 2,

In [57]:
block26hundredCount = 0
block26twodredCount = 0
block26threedredCount = 0
block26fourdredCount = 0
block26fivedredCount = 0
for i in block26pageCount.values():
    if i >= 100:
        block26hundredCount += 1
    if i >= 200:
        block26twodredCount += 1
    if i >= 300: 
        block26threedredCount += 1
    if i >= 400:
        block26fourdredCount += 1
    if i >= 500:
        block26fivedredCount += 1
print(block26hundredCount)
print(block26twodredCount)
print(block26threedredCount)
print(block26fourdredCount)
print(block26fivedredCount)

2
1
0
0
0


In [58]:
print(len(block26pageCount.keys()))

67
